### PR TITLE
fix xcode 10.2 issue

### PR DESCRIPTION
**Pull request by OPADA-Eng**
Fix issue #53

### CODE REVIEW

**Comment by tralves** [comment]
Thanks @OPADA-Eng! I ran into this issue today!
(turns out my project isn't using this plugin after all, but if it were, you had saved my life)

**Comment by FranciZ** [comment]
@OPADA-Eng the fix doesn't work for me. The init function is undefined if updating version to 13. I guess it was deprecated. The version that worked for me is `12.1.3`.

**Comment by OPADA-Eng** [comment]
@FranciZ Thanks For providing us with this information.
I made the PR refer to the version you mentioned.

**Comment by OPADA-Eng** [comment]
@naderio Can you please merge this pull request

**Comment by naderio** [comment]
@OPADA-Eng apologies for not checking this, I've not received a notification until your mention.
I'll review and merge if all good

**Comment by OPADA-Eng** [comment]
@naderio No problem, Thanks in advance.

**Comment by naderio** [comment]
@OPADA-Eng are you sure that your change do not break anything? last time iOS dependency upgrade were attempted, it broke the code

**Comment by OPADA-Eng** [comment]
I have tested most functions and it's working fine.

**Comment by OPADA-Eng** [comment]
@naderio Any news with this?

**Comment by mastashake08** [comment]
PLEASE MERGE THIS

**Pull request merged**
